services:
  - type: web
    name: energy-transition-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
